runtime: nodejs20
service: default
handlers:
  - url: /notes
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
  - url: /
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
  - url: /(.+)
    static_files: dist/\1
    upload: dist/(.+)
    secure: always
  - url: /.*
    script: auto
    secure: always
env_variables:
  NODE_ENV: production
  HTTP_HEADERS: '{"Strict-Transport-Security": "max-age=31536000; includeSubDomains"}'